#ifndef SIMD_INSTRUCTION_TYPE_H
#define SIMD_INSTRUCTION_TYPE_H

enum INSTRUCTION_TYPE
{
	INSTRUCTION_NORMAL,
	INSTRUCTION_SSE2,
	INSTRUCTION_SSSE3,
	INSTRUCTION_AVX2
};

#endif /* SIMD_INSTRUCTION_TYPE_H */
